### ISSUE TITLE
Add CDN detect for Chinese developer

### ISSUE THREAD

**Issue by huacnlee** [rubygems/rubygems.org-configs#2]
Hi Evan,

We are talked about the RubyGems install issues in China in 3 years ago.

> NOTE: China Internet can't access Amazon S3.

```
$ gem source -a https://rubygems.org
Error fetching https://rubygems.org:
    Errno::ETIMEDOUT: Operation timed out - connect(2) for "s3.amazonaws.com" port 443 (https://api.rubygems.org/specs.4.8.gz)
```

Yes, After you help, we created a mirror site [http://ruby.taobao.org](http://ruby.taobao.org/index_en.html) and that site help many of Chinese Ruby developer to install Gems.

But in a long-term use, we found that isn't best way:
1. So many newbies don’t know how to change the mirror;
2. Some time `RubyTaobao Mirror` can access rubygems.org official CDN (S3), so the sync progress is very slow, and unstable (Sometimes may lose gem version).
   
   We ([Ruby China](https://ruby-china.org) - Ruby Community Site in China) talked about how to improve Chinese developers to use RubyGems.

Why not change rubygems.org official to detect IP Address (Nginx GEO Module), when install access from China, use CDN in China (etc. http://cn-mm.rubygems.org), not Amazon S3.

---

We got a lot of sponsors can bear the cost of CDN in China.

**Comment by lgn21st** [comment]
:+1: :+1: :+1:

**Comment by lgn21st** [comment]
Hi Evan,

I'm another core member of [RubyChina](https://ruby-china.org/) as well.

The main problem is the connection between our mirror site and S3 is very poor, very unstable and low speed. we got lots of support from local vender like CDN or host for free, and we hopeful that we can figure it out. thank you very much.

**Comment by chloerei** [comment]
I'm a member of RubyChina. But I don't want rubygems.org auto switch chinese-only CDN, I want to reach the orignal rubygems.

It's better to maintain a separate mirrors, and manually config by who need it.

**Comment by huacnlee** [comment]
@rei CDN is not mirror, It just a cacheable proxy, so it safe, stable.

Actually, rubygems.org has did some thing like that at some times in the past. It's names Tokyo-MM, rubygems Nginx will redirect Access from China to Tokoy-MM with GEO IP.
